/*
	Function:1.1
	Author:zhl
	Build_Date:2018-3-19
	Version:1.0
*/

//1.公共变量声明块........................................................
/*varcharacter=document.getElementById("1");
varillegal=document.getElementById("2");
varmaintain=document.getElementById("3");
vartravel=document.getElementById("4");*/
/*varid1=document.getElementById("id1");
varid2=document.getElementById("id2");
varid3=document.getElementById("id3");
varid4=document.getElementById("id4");*/
//2.函数定义块...........................................................
		$("#all_bottom").click(function(){
			$("#all_bottom").addClass("active");//追加样式
			$("#capital_bottom").removeClass();//删除样式
			$("#equity_bottom").removeClass();//删除样式
			$("#estate_bottom").removeClass();//删除样式
			$("#asset_bottom").removeClass();//删除样式
			$("#money_bottom").removeClass();//删除样式
			$("#judicial_bottom").removeClass();//删除样式
			$("#wage_bottom").removeClass();//删除样式
			$("#other_bottom").removeClass();//删除样式
			$(".allinfo").css("display","block");
			$(".capitalinfo").css("display","none");
			$(".equityinfo").css("display","none");
			$(".estateinfo").css("display","none");
			$(".assetinfo").css("display","none");
			$(".moneyinfo").css("display","none");
			$(".judicialinfo").css("display","none");
			$(".wageinfo").css("display","none");
			$(".otherinfo").css("display","none");
			});
		$("#capital_bottom").click(function(){
			$("#all_bottom").removeClass();//删除样式
			$("#capital_bottom").addClass("active");//追加样式
			$("#equity_bottom").removeClass();//删除样式
			$("#estate_bottom").removeClass();//删除样式
			$("#asset_bottom").removeClass();//删除样式
			$("#money_bottom").removeClass();//删除样式
			$("#judicial_bottom").removeClass();//删除样式
			$("#wage_bottom").removeClass();//删除样式
			$("#other_bottom").removeClass();//删除样式
			$(".allinfo").css("display","none");
			$(".capitalinfo").css("display","block");
			$(".equityinfo").css("display","none");
			$(".estateinfo").css("display","none");
			$(".assetinfo").css("display","none");
			$(".moneyinfo").css("display","none");
			$(".judicialinfo").css("display","none");
			$(".wageinfo").css("display","none");
			$(".otherinfo").css("display","none");
			});
		$("#equity_bottom").click(function(){
			$("#all_bottom").removeClass();//删除样式
			$("#capital_bottom").removeClass();//删除样式
			$("#equity_bottom").addClass("active");//追加样式
			$("#estate_bottom").removeClass();//删除样式
			$("#asset_bottom").removeClass();//删除样式
			$("#money_bottom").removeClass();//删除样式
			$("#judicial_bottom").removeClass();//删除样式
			$("#wage_bottom").removeClass();//删除样式
			$("#other_bottom").removeClass();//删除样式
			$(".allinfo").css("display","none");
			$(".capitalinfo").css("display","none");
			$(".equityinfo").css("display","block");
			$(".estateinfo").css("display","none");
			$(".assetinfo").css("display","none");
			$(".moneyinfo").css("display","none");
			$(".judicialinfo").css("display","none");
			$(".wageinfo").css("display","none");
			$(".otherinfo").css("display","none");
			});
		$("#estate_bottom").click(function(){
			$("#all_bottom").removeClass();//删除样式
			$("#capital_bottom").removeClass();//删除样式
			$("#equity_bottom").removeClass();//删除样式
			$("#estate_bottom").addClass("active");//追加样式
			$("#asset_bottom").removeClass();//删除样式
			$("#money_bottom").removeClass();//删除样式
			$("#judicial_bottom").removeClass();//删除样式
			$("#wage_bottom").removeClass();//删除样式
			$("#other_bottom").removeClass();//删除样式
			$(".allinfo").css("display","none");
			$(".capitalinfo").css("display","none");
			$(".equityinfo").css("display","none");
			$(".estateinfo").css("display","block");
			$(".assetinfo").css("display","none");
			$(".moneyinfo").css("display","none");
			$(".judicialinfo").css("display","none");
			$(".wageinfo").css("display","none");
			$(".otherinfo").css("display","none");
			});
		$("#asset_bottom").click(function(){
			$("#all_bottom").removeClass();//删除样式
			$("#capital_bottom").removeClass();//删除样式
			$("#equity_bottom").removeClass();//删除样式
			$("#estate_bottom").removeClass();//删除样式
			$("#asset_bottom").addClass("active");//追加样式
			$("#money_bottom").removeClass();//删除样式
			$("#judicial_bottom").removeClass();//删除样式
			$("#wage_bottom").removeClass();//删除样式
			$("#other_bottom").removeClass();//删除样式
			$(".allinfo").css("display","none");
			$(".capitalinfo").css("display","none");
			$(".equityinfo").css("display","none");
			$(".estateinfo").css("display","none");
			$(".assetinfo").css("display","block");
			$(".moneyinfo").css("display","none");
			$(".judicialinfo").css("display","none");
			$(".wageinfo").css("display","none");
			$(".otherinfo").css("display","none");
			});
		$("#money_bottom").click(function(){
			$("#all_bottom").removeClass();//删除样式
			$("#capital_bottom").removeClass();//删除样式
			$("#equity_bottom").removeClass();//删除样式
			$("#estate_bottom").removeClass();//删除样式
			$("#asset_bottom").removeClass();//删除样式
			$("#money_bottom").addClass("active");//追加样式
			$("#judicial_bottom").removeClass();//删除样式
			$("#wage_bottom").removeClass();//删除样式
			$("#other_bottom").removeClass();//删除样式
			$(".allinfo").css("display","none");
			$(".capitalinfo").css("display","none");
			$(".equityinfo").css("display","none");
			$(".estateinfo").css("display","none");
			$(".assetinfo").css("display","none");
			$(".moneyinfo").css("display","block");
			$(".judicialinfo").css("display","none");
			$(".wageinfo").css("display","none");
			$(".otherinfo").css("display","none");
			});
		$("#judicial_bottom").click(function(){
			$("#all_bottom").removeClass();//删除样式
			$("#capital_bottom").removeClass();//删除样式
			$("#equity_bottom").removeClass();//删除样式
			$("#estate_bottom").removeClass();//删除样式
			$("#asset_bottom").removeClass();//删除样式
			$("#money_bottom").removeClass();//删除样式
			$("#judicial_bottom").addClass("active");//追加样式
			$("#wage_bottom").removeClass();//删除样式
			$("#other_bottom").removeClass();//删除样式
			$(".allinfo").css("display","none");
			$(".capitalinfo").css("display","none");
			$(".equityinfo").css("display","none");
			$(".estateinfo").css("display","none");
			$(".assetinfo").css("display","none");
			$(".moneyinfo").css("display","none");
			$(".judicialinfo").css("display","block");
			$(".wageinfo").css("display","none");
			$(".otherinfo").css("display","none");
			});
		$("#wage_bottom").click(function(){
			$("#all_bottom").removeClass();//删除样式
			$("#capital_bottom").removeClass();//删除样式
			$("#equity_bottom").removeClass();//删除样式
			$("#estate_bottom").removeClass();//删除样式
			$("#asset_bottom").removeClass();//删除样式
			$("#money_bottom").removeClass();//删除样式
			$("#judicial_bottom").removeClass();//删除样式
			$("#wage_bottom").addClass("active");//追加样式
			$("#other_bottom").removeClass();//删除样式
			$(".allinfo").css("display","none");
			$(".capitalinfo").css("display","none");
			$(".equityinfo").css("display","none");
			$(".estateinfo").css("display","none");
			$(".assetinfo").css("display","none");
			$(".moneyinfo").css("display","none");
			$(".judicialinfo").css("display","none");
			$(".wageinfo").css("display","block");
			$(".otherinfo").css("display","none");
			});
		$("#other_bottom").click(function(){
			$("#all_bottom").removeClass();//删除样式
			$("#capital_bottom").removeClass();//删除样式
			$("#equity_bottom").removeClass();//删除样式
			$("#estate_bottom").removeClass();//删除样式
			$("#asset_bottom").removeClass();//删除样式
			$("#money_bottom").removeClass();//删除样式
			$("#judicial_bottom").removeClass();//删除样式
			$("#wage_bottom").removeClass();//删除样式
			$("#other_bottom").addClass("active");//追加样式
			$(".allinfo").css("display","none");
			$(".capitalinfo").css("display","none");
			$(".equityinfo").css("display","none");
			$(".estateinfo").css("display","none");
			$(".assetinfo").css("display","none");
			$(".moneyinfo").css("display","none");
			$(".judicialinfo").css("display","none");
			$(".wageinfo").css("display","none");
			$(".otherinfo").css("display","block");
			});
//3.事件注册块...........................................................



//4.初始化块............................................................
